import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Download, FileText, Code, ChevronDown } from 'lucide-react';
import { useSpotlightStoreV2 } from '../../../stores/spotlightStoreV2';

const ExportMenu = () => {
  const { route, getCityName } = useSpotlightStoreV2();
  const [isOpen, setIsOpen] = useState(false);

  const handleExportJSON = () => {
    if (!route) return;

    const exportData = {
      route: {
        cities: route.cities.map((city, index) => ({
          name: getCityName(city.city),
          coordinates: city.coordinates,
          nights: city.nights,
          activities: city.activities,
          restaurants: city.restaurants,
          accommodation: city.accommodation,
          order: index + 1
        })),
        landmarks: route.landmarks || [],
        totalCities: route.cities.length,
        totalNights: route.cities.reduce((sum, city) => sum + (city.nights || 0), 0)
      },
      metadata: {
        exportedAt: new Date().toISOString(),
        agent: route.agent || 'adventure'
      }
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], {
      type: 'application/json'
    });

    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `route-${Date.now()}.json`;
    a.click();

    URL.revokeObjectURL(url);
    setIsOpen(false);
  };

  const handleExportPDF = async () => {
    if (!route) return;

    try {
      // Dynamic import of jsPDF
      const { default: jsPDF } = await import('jspdf');

      const doc = new jsPDF();
      let yPos = 20;

      // Title
      doc.setFontSize(20);
      doc.setTextColor(6, 77, 81); // Agent primary color
      doc.text('Road Trip Itinerary', 20, yPos);
      yPos += 15;

      // Route summary
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.text(`Total Cities: ${route.cities.length}`, 20, yPos);
      yPos += 8;
      doc.text(`Total Nights: ${route.cities.reduce((sum, city) => sum + (city.nights || 0), 0)}`, 20, yPos);
      yPos += 15;

      // Cities
      doc.setFontSize(16);
      doc.text('Cities', 20, yPos);
      yPos += 10;

      doc.setFontSize(11);
      route.cities.forEach((city, index) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }

        const cityName = getCityName(city.city);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text(`${index + 1}. ${cityName}`, 20, yPos);
        yPos += 7;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        if (city.nights) {
          doc.text(`   Nights: ${city.nights}`, 20, yPos);
          yPos += 6;
        }

        if (city.activities && city.activities.length > 0) {
          doc.text(`   Activities: ${city.activities.length}`, 20, yPos);
          yPos += 6;
        }

        yPos += 5;
      });

      // Landmarks
      if (route.landmarks && route.landmarks.length > 0) {
        if (yPos > 250) {
          doc.addPage();
          yPos = 20;
        }

        yPos += 10;
        doc.setFontSize(16);
        doc.text('Landmarks', 20, yPos);
        yPos += 10;

        doc.setFontSize(11);
        route.landmarks.forEach((landmark, index) => {
          if (yPos > 270) {
            doc.addPage();
            yPos = 20;
          }

          doc.setFontSize(12);
          doc.setFont('helvetica', 'bold');
          doc.text(`${index + 1}. ${landmark.name}`, 20, yPos);
          yPos += 7;

          doc.setFont('helvetica', 'normal');
          doc.setFontSize(10);
          if (landmark.detourKm !== undefined && landmark.detourMinutes !== undefined) {
            doc.text(`   Detour: +${landmark.detourKm.toFixed(1)} km, +${Math.round(landmark.detourMinutes)} min`, 20, yPos);
            yPos += 6;
          }

          yPos += 5;
        });
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      doc.text(`Generated by RoadTrip - ${new Date().toLocaleDateString()}`, 20, 285);

      doc.save(`route-${Date.now()}.pdf`);
      setIsOpen(false);
    } catch (error) {
      console.error('PDF export error:', error);
      alert('Failed to export PDF. Please try again.');
    }
  };

  if (!route) return null;

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 rounded-lg border border-gray-200 bg-gray-100 px-4 py-2 text-sm font-medium text-gray-700 transition-all hover:bg-gray-200 hover:shadow-md"
      >
        <Download className="h-4 w-4" />
        <span>Export</span>
        <ChevronDown className={`h-4 w-4 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
      </button>

      <AnimatePresence>
        {isOpen && (
          <>
            {/* Backdrop */}
            <div
              className="fixed inset-0 z-40"
              onClick={() => setIsOpen(false)}
            />

            {/* Menu */}
            <motion.div
              initial={{ opacity: 0, y: -10, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: -10, scale: 0.95 }}
              transition={{ duration: 0.15 }}
              className="absolute right-0 top-full mt-2 w-48 rounded-lg border border-gray-200 bg-white shadow-xl z-50 overflow-hidden"
            >
              <div className="p-2">
                <button
                  onClick={handleExportJSON}
                  className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left transition-colors hover:bg-gray-50"
                >
                  <Code className="h-4 w-4 text-gray-600" />
                  <div className="flex-1">
                    <div className="text-sm font-medium text-gray-900">JSON</div>
                    <div className="text-xs text-gray-500">Export route data</div>
                  </div>
                </button>

                <button
                  onClick={handleExportPDF}
                  className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left transition-colors hover:bg-gray-50"
                >
                  <FileText className="h-4 w-4 text-gray-600" />
                  <div className="flex-1">
                    <div className="text-sm font-medium text-gray-900">PDF</div>
                    <div className="text-xs text-gray-500">Printable itinerary</div>
                  </div>
                </button>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
};

export default ExportMenu;
